//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResto2.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string orderID { get; set; }
        public string productID { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
    }
}
